import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const lovinSummer = localFont({
  src: "../assets/fonts/lovinSummer.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lovinSummer.className} antialiased`}>{children}</body>
    </html>
  );
}
